server {
	listen 80;
	server_name localhost;

	absolute_redirect off;
	port_in_redirect off;

	root /var/www/html;
	index index.php index.html;

	error_page 404 /404.html;
    location = /404.html {
        root /var/www/html/project1/;
        internal;
    }

    location ~* /project1/vendor/ {
        deny all;
        return 403;
    }

	location /project1 {
		try_files $uri $uri/ /project1/index.php?$query_string;
	}

	location / {
		return 301 /project1/;
	}

	location ~ \.php$ {
		include fastcgi_params;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	location ~ /\.ht {
		deny all;
	}
}